"""empty message

Revision ID: 35416c54d48f
Revises: f1f805cda95a
Create Date: 2024-05-15 14:56:07.385751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35416c54d48f'
down_revision = 'f1f805cda95a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person_movie', sa.Column('people_id', sa.Integer(), nullable=True))
    op.add_column('person_movie', sa.Column('movies_id', sa.Integer(), nullable=True))
    op.drop_constraint('person_movie_course_id_fkey', 'person_movie', type_='foreignkey')
    op.drop_constraint('person_movie_student_id_fkey', 'person_movie', type_='foreignkey')
    op.create_foreign_key(None, 'person_movie', 'Movies', ['movies_id'], ['id'])
    op.create_foreign_key(None, 'person_movie', 'People', ['people_id'], ['id'])
    op.drop_column('person_movie', 'student_id')
    op.drop_column('person_movie', 'course_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person_movie', sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('person_movie', sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'person_movie', type_='foreignkey')
    op.drop_constraint(None, 'person_movie', type_='foreignkey')
    op.create_foreign_key('person_movie_student_id_fkey', 'person_movie', 'People', ['student_id'], ['id'])
    op.create_foreign_key('person_movie_course_id_fkey', 'person_movie', 'Movies', ['course_id'], ['id'])
    op.drop_column('person_movie', 'movies_id')
    op.drop_column('person_movie', 'people_id')
    # ### end Alembic commands ###
