"""empty message

Revision ID: 40085b546757
Revises: d8a7d2a545d9
Create Date: 2024-05-14 15:47:05.171574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40085b546757'
down_revision = 'd8a7d2a545d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Movies', sa.Column('person_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Movies', 'People', ['person_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Movies', type_='foreignkey')
    op.drop_column('Movies', 'person_id')
    # ### end Alembic commands ###
