"""empty message

Revision ID: aafaa2e149c8
Revises: 40085b546757
Create Date: 2024-05-15 13:12:04.074702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aafaa2e149c8'
down_revision = '40085b546757'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Movies', 'person_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Movies', 'person_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
