"""empty message

Revision ID: e0cb49f92bb2
Revises: b4f0714132f7
Create Date: 2024-05-17 16:36:12.268330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0cb49f92bb2'
down_revision = 'b4f0714132f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Movies', sa.Column('person_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Movies', 'People', ['person_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Movies', type_='foreignkey')
    op.drop_column('Movies', 'person_id')
    # ### end Alembic commands ###
